pur_beurre/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls')),
    path('', include('substitute.urls')),
    path(
        'legal/',
        TemplateView.as_view(template_name='legal.html'),
        name='legal'
    )
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

substitute/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from substitute.views.favorite import (AddFavoriteView, FavoritesView,
                                       RemoveFavoriteView)
from substitute.views.home import HomeView
from substitute.views.product import ProductDetailView, SearchResultView

app_name = 'substitute'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('substitute', SearchResultView.as_view(), name='search'),
    path('product/<int:pk>', ProductDetailView.as_view(), name='prod-detail'),
    path('favorites/', login_required(FavoritesView.as_view()), name='all_favorites'),
    path(
        'remove_favorite/<int:pk>',
        login_required(RemoveFavoriteView.as_view()),
        name='remove_favorite'
    ),
    path(
        'add_favorite/<int:pk>',
        login_required(AddFavoriteView.as_view()),
        name='add_favorite'
    ),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from django.views.generic import TemplateView

from users.views.login import EmailLoginView
from users.views.signup import EmailSignUpView

app_name = 'users'

urlpatterns = [
    path('signup/', EmailSignUpView.as_view(), name='signup'),
    path('login/', EmailLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path(
        'account/',
        TemplateView.as_view(template_name='users/account.html'),
        name='account'
    )
]

substitute/models/brand.py
from django.db import models


class Brand(models.Model):
    name = models.CharField(max_length=255, unique=True)
    products = models.ManyToManyField("Product",
                                      related_name="brands",
                                      blank=True)

    def __str__(self):
        return f"{self.name}"

templates/navbar/partials/brand.html
{% load static %}
<a class="navbar-brand px-3" href={% url 'substitute:home' %}>
  <img src={% static 'assets/img/logo_pur_beurre.png' class="navbar-toggler-icon" %} height="30em"/>
  Pur Beurre
</a>

templates/navbar/partials/logged_in.html
{% load static %}
  <li class="nav-item">
    <a class="nav-link active" aria-current="page" href="{% url 'users:account' %}">
      <i class="bi bi-person"> Mon compte</i>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'substitute:all_favorites' %}">
      <img src={% static 'assets/icons/noun-carrot-29691.png' %} height="30em"/> Mes aliments
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'users:logout' %}" >
      <i class="bi bi-box-arrow-right"> Déconnexion</i>
    </a>
  </li>

templates/navbar/partials/logged_out.html
  <li class="nav-item">
    <a class="nav-link" href="{% url 'users:login' %}">
      <i class="bi bi-box-arrow-in-right"> Se connecter</i>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'users:signup' %}">
      <i class="bi bi-person-plus-fill"> S'enregistrer</i>
    </a>
  </li>