pur_beurre/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls')),
    path('', include('substitute.urls')),
    path(
        'legal/',
        TemplateView.as_view(template_name='legal.html'),
        name='legal'
    )
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

substitute/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from substitute.views.favorite import (AddFavoriteView, FavoritesView,
                                       RemoveFavoriteView)
from substitute.views.home import HomeView
from substitute.views.product import ProductDetailView, SearchResultView

app_name = 'substitute'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('substitute', SearchResultView.as_view(), name='search'),
    path('product/<int:pk>', ProductDetailView.as_view(), name='prod-detail'),
    path('favorites/', login_required(FavoritesView.as_view()), name='all_favorites'),
    path(
        'remove_favorite/<int:pk>',
        login_required(RemoveFavoriteView.as_view()),
        name='remove_favorite'
    ),
    path(
        'add_favorite/<int:pk>',
        login_required(AddFavoriteView.as_view()),
        name='add_favorite'
    ),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from django.views.generic import TemplateView

from users.views.login import EmailLoginView
from users.views.signup import EmailSignUpView

app_name = 'users'

urlpatterns = [
    path('signup/', EmailSignUpView.as_view(), name='signup'),
    path('login/', EmailLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path(
        'account/',
        TemplateView.as_view(template_name='users/account.html'),
        name='account'
    )
]

templates/navbar/basic.html
{% load bootstrap5 %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  {% include "navbar/partials/brand.html" %}
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="d-flex navbar-nav ms-auto">
      <li class="nav-item">
        <form action="{% url 'substitute:search' %}" method="get" class="d-flex">
          {% bootstrap_form searchform layout='inline' %}
        </form>
      </li>
    {% if user.is_authenticated %}
      {% include "navbar/partials/logged_in.html" %}
    {% else %}
      {% include "navbar/partials/logged_out.html" %}
    {% endif %}
    </ul>
  </div>
</nav>