pur_beurre/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls')),
    path('', include('substitute.urls')),
    path(
        'legal/',
        TemplateView.as_view(template_name='legal.html'),
        name='legal'
    )
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

substitute/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from substitute.views.favorite import (AddFavoriteView, FavoritesView,
                                       RemoveFavoriteView)
from substitute.views.home import HomeView
from substitute.views.product import ProductDetailView, SearchResultView

app_name = 'substitute'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('substitute', SearchResultView.as_view(), name='search'),
    path('product/<int:pk>', ProductDetailView.as_view(), name='prod-detail'),
    path('favorites/', login_required(FavoritesView.as_view()), name='all_favorites'),
    path(
        'remove_favorite/<int:pk>',
        login_required(RemoveFavoriteView.as_view()),
        name='remove_favorite'
    ),
    path(
        'add_favorite/<int:pk>',
        login_required(AddFavoriteView.as_view()),
        name='add_favorite'
    ),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from django.views.generic import TemplateView

from users.views.login import EmailLoginView
from users.views.signup import EmailSignUpView

app_name = 'users'

urlpatterns = [
    path('signup/', EmailSignUpView.as_view(), name='signup'),
    path('login/', EmailLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path(
        'account/',
        TemplateView.as_view(template_name='users/account.html'),
        name='account'
    )
]

substitute/models/brand.py
from django.db import models


class Brand(models.Model):
    name = models.CharField(max_length=255, unique=True)
    products = models.ManyToManyField("Product",
                                      related_name="brands",
                                      blank=True)

    def __str__(self):
        return f"{self.name}"

substitute/models/category.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)
    products = models.ManyToManyField("Product",
                                      related_name="categories",
                                      blank=True)

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name_plural = "categories"

substitute/models/favorite.py
from django.db import models


class Favorite(models.Model):
    user = models.ForeignKey("users.UserProfile",
                             related_name=("favorites"),
                             on_delete=models.CASCADE)
    product = models.ForeignKey("Product",
                                related_name=("favorites"),
                                on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.username}=>{self.product.name}"

substitute/models/product.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=255, unique=True)
    url = models.URLField(blank=False)
    nutriscore = models.CharField(max_length=1)
    barcode = models.CharField(max_length=255, unique=True)
    image_url = models.URLField(blank=False)
    image_nutri = models.URLField(blank=False)

    def __str__(self):
        return f"{self.name}"

substitute/models/store.py
from django.db import models


class Store(models.Model):
    name = models.CharField(max_length=255, unique=True)
    products = models.ManyToManyField("Product",
                                      related_name="stores",
                                      blank=True)

    def __str__(self):
        return f"{self.name}"

substitute/forms/favorite.py
from django import forms

from substitute.models.favorite import Favorite
from substitute.models.product import Product


class FavForm(forms.ModelForm):
    product = forms.ModelChoiceField(queryset=Product.objects.all())

    class Meta:
        model = Favorite
        fields = ["product"]

substitute/forms/search.py
from django import forms


class SearchForm(forms.Form):
    search = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Saisir un nom de produit'}))

substitute/views/favorite.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect
from django.views.generic.edit import CreateView, DeleteView
from django.views.generic.list import ListView

from substitute.forms.favorite import FavForm
from substitute.models.favorite import Favorite
from substitute.models.product import Product
from substitute.views.utils import get_msg


class AddFavoriteView(CreateView):
    model = Favorite
    form_class = FavForm

    def post(self, request, *args, **kwargs):
        prod = get_object_or_404(Product, pk=kwargs['pk'])
        form = FavForm(request.POST)
        if form.is_valid():
            unsaved_fav = form.save(commit=False)
            unsaved_fav.user = request.user
            unsaved_fav.save()
            messages.success(request, get_msg(prod, "add", "success"))
        else:
            messages.error(request, get_msg(prod, "add", "fail"))

        return redirect(request.META['HTTP_REFERER'])


class RemoveFavoriteView(DeleteView):
    model = Favorite
    form_class = FavForm

    def post(self, request, *args, **kwargs):
        fav = get_object_or_404(Favorite, product=kwargs['pk'], user=request.user)
        form = FavForm(request.POST)
        if form.is_valid():
            fav.delete()
            messages.success(request, get_msg(fav.product, "delete", "success"))
        else:
            messages.error(request, get_msg(fav.product, "delete", "fail"))
        return redirect(request.META['HTTP_REFERER'])


class FavoritesView(ListView):
    http_method_names = ['get', 'options']
    template_name = 'substitute/favorites.html'
    model = Favorite
    paginate_by = 6

    def get_queryset(self):
        return self.request.user.all_favs_prods

substitute/views/home.py
from django.views.generic.base import TemplateView


class HomeView(TemplateView):
    template_name = 'home.html'

substitute/views/product.py
from django.db.models import Count, Q
from django.shortcuts import get_object_or_404, render
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormMixin
from django.views.generic.list import ListView

from substitute.forms.search import SearchForm
from substitute.models.product import Product


class SearchResultView(ListView, FormMixin):
    http_method_names = ['get', 'options']
    form_class = SearchForm
    template_name = 'substitute/search_results.html'
    model = Product
    paginate_by = 6

    def get_queryset(self):
        search_text = self.request.GET.get('search', None)
        if search_text:
            return self.get_prod_by_name(search_text)

    @staticmethod
    def get_prod_by_name(search_text):
        return Product.objects.filter(
                Q(name__icontains=search_text.lower().strip())
            ).order_by('-nutriscore')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('search')
        return context


class ProductDetailView(DetailView):
    model = Product

    def get(self, request, *args, **kwargs):
        product = get_object_or_404(Product, pk=kwargs['pk'])
        substitutes = self._refine_substitutes(product, self._get_substitutes(product))
        context = {'product': product, 'substitutes': substitutes}
        return render(request, 'substitute/product_detail.html', context)

    @staticmethod
    def _get_substitutes(product):
        return Product.objects.annotate(
            common_categories=Count(
                "categories",
                filter=Q(categories__in=product.categories.all())
            )
        ).annotate(
            num_categories=Count("categories")
        )

    def _refine_substitutes(self, product, substitutes):
        no_product_categories = product.categories.all().count()
        substitutes.filter(common_categories=no_product_categories)
        if product.nutriscore == "a":
            substitutes = substitutes.filter(nutriscore__lte=product.nutriscore)
        else:
            substitutes = substitutes.filter(nutriscore__lt=product.nutriscore)

        return substitutes.exclude(
            pk=self.kwargs['pk']
        ).order_by(
            "nutriscore", "num_categories", "-common_categories"
        )[:3]

substitute/views/utils.py
def get_msg(prod, procedure, outcome):
    if procedure == "delete":
        if outcome == "success":
            return (
                "Le produit suivant a bien été supprimé de vos favoris:\n"
                f"{prod}"
            )
        elif outcome == "fail":
            return (
                "Le produit suivant n'a pas été supprimé de vos favoris:\n"
                f"{prod}"
            )
    elif procedure == "add":
        if outcome == "success":
            return (
                "Le produit suivant a bien été enregistré dans vos favoris:\n"
                f"{prod}"
            )
        elif outcome == "fail":
            return (
                "Le produit suivant n'a pas été enregistré dans vos favoris:\n"
                f"{prod}"
            )
    else:
        raise AttributeError("You're not asking for the right message !")

templates/substitute/partials/list_title.html
{% if detail_view %}
    <h3 class="text-white text-center">Voici {{ prod_list.count }} produits de substitutions:</h3>
{% elif favorites %}
    <h3 class="text-white text-center">Voici vos Favoris:</h3>
{% else %}
    <h3 class="text-white text-center">Voici les produits qui ressemble à:</h3>
    <h3 class="text-black text-center">{{ query }}</h3>
{% endif %}

templates/substitute/partials/pagination.html
<div class="pagination justify-content-center">
  <span class="page-links">
    {% if page_obj.has_previous %}
      <a href="?search={{ query }}&page=1">&laquo; Début</a>
      <a href="?search={{ query }}&page={{ page_obj.previous_page_number }}">Précédent</a>
    {% endif %}

    <span class="current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>

    {% if page_obj.has_next %}
      <a href="?search={{ query }}&page={{ page_obj.next_page_number }}">Suivant</a>
      <a href="?search={{ query }}&page={{ page_obj.paginator.num_pages }}">Fin &raquo;</a>
    {% endif %}
  </span>
</div>

templates/substitute/partials/product_list.html
<section class="page-section bg-primary py-0" id="resultat">
    <div class="container-fluid p-4">
      <div class="row g-4">
        {% if prod_list %}
          <div class="col-12">
            {% include "substitute/partials/list_title.html" with prod_list=prod_list %}
          </div>
          {% for alt_prod in prod_list %}
            <div class="col-md-4 col-sm-6 px-4">
              <div class="card h-100">
                <div class="card-body d-flex flex-column h-100">
                  <div class="d-flex flex-grow-1 justify-content-center align-items-center">
                    <a href="{% url 'substitute:prod-detail' pk=alt_prod.pk %}">
                      <img src="{{ alt_prod.image_url }}" class="img-fluid my-auto mx-auto">
                    </a>
                  </div>
                  <div>
                    <h5 class="card-title align-items-bottom text-center">
                    {{ alt_prod.name }}
                    </h5>
                    <p class="card-text align-items-bottom text-center">
                      Nutriscore: {{ alt_prod.nutriscore }}
                    </p>
                    <div class="text-center mx-auto ">
                      <a href="{% url 'substitute:prod-detail' pk=alt_prod.pk %}" class="btn btn-primary">
                        Accéder à la fiche produit
                      </a>
                      {% if user.is_authenticated %}
                        {% if alt_prod in user.all_favs_prods %}
                          <form method='post' action="{% url 'substitute:remove_favorite' alt_prod.pk %}">
                            {% csrf_token %}
                            <input type='hidden' name='product'  id="id_product" value="{{ alt_prod.pk }}"/>
                            <button class="btn btn-primary" type='submit'>Supprimer des favoris</button>
                          </form>
                        {% elif alt_prod not in user.all_favs_prods %}
                          <form method='post' action="{% url 'substitute:add_favorite' alt_prod.pk %}">
                            {% csrf_token %}
                            <input type="hidden" name="product" id="id_product" value="{{ alt_prod.pk }}"/>
                            <button class="btn btn-primary" type='submit'>Ajouter aux favoris</button>
                          </form>
                        {% endif %}
                      {% endif %}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
        {% elif favorites %}
          <p class="text-center">
            Vous n'avez aucun favoris d'enregistré.
          </p>
        {% else %}
          <p class="text-center">
            Nous n'avons aucun produit de substitution pertinent à vous conseillez.
          </p>
        {% endif %}
      </div>
    </div>
  </section>