pur_beurre/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls')),
    path('', include('substitute.urls')),
    path(
        'legal/',
        TemplateView.as_view(template_name='legal.html'),
        name='legal'
    )
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

substitute/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from substitute.views.favorite import (AddFavoriteView, FavoritesView,
                                       RemoveFavoriteView)
from substitute.views.home import HomeView
from substitute.views.product import ProductDetailView, SearchResultView

app_name = 'substitute'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('substitute', SearchResultView.as_view(), name='search'),
    path('product/<int:pk>', ProductDetailView.as_view(), name='prod-detail'),
    path('favorites/', login_required(FavoritesView.as_view()), name='all_favorites'),
    path(
        'remove_favorite/<int:pk>',
        login_required(RemoveFavoriteView.as_view()),
        name='remove_favorite'
    ),
    path(
        'add_favorite/<int:pk>',
        login_required(AddFavoriteView.as_view()),
        name='add_favorite'
    ),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from django.views.generic import TemplateView

from users.views.login import EmailLoginView
from users.views.signup import EmailSignUpView

app_name = 'users'

urlpatterns = [
    path('signup/', EmailSignUpView.as_view(), name='signup'),
    path('login/', EmailLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path(
        'account/',
        TemplateView.as_view(template_name='users/account.html'),
        name='account'
    )
]

substitute/models/brand.py
from django.db import models


class Brand(models.Model):
    name = models.CharField(max_length=255, unique=True)
    products = models.ManyToManyField("Product",
                                      related_name="brands",
                                      blank=True)

    def __str__(self):
        return f"{self.name}"

substitute/models/category.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)
    products = models.ManyToManyField("Product",
                                      related_name="categories",
                                      blank=True)

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name_plural = "categories"

substitute/models/favorite.py
from django.db import models


class Favorite(models.Model):
    user = models.ForeignKey("users.UserProfile",
                             related_name=("favorites"),
                             on_delete=models.CASCADE)
    product = models.ForeignKey("Product",
                                related_name=("favorites"),
                                on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.username}=>{self.product.name}"

substitute/models/product.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=255, unique=True)
    url = models.URLField(blank=False)
    nutriscore = models.CharField(max_length=1)
    barcode = models.CharField(max_length=255, unique=True)
    image_url = models.URLField(blank=False)
    image_nutri = models.URLField(blank=False)

    def __str__(self):
        return f"{self.name}"

substitute/models/store.py
from django.db import models


class Store(models.Model):
    name = models.CharField(max_length=255, unique=True)
    products = models.ManyToManyField("Product",
                                      related_name="stores",
                                      blank=True)

    def __str__(self):
        return f"{self.name}"

substitute/forms/favorite.py
from django import forms

from substitute.models.favorite import Favorite
from substitute.models.product import Product


class FavForm(forms.ModelForm):
    product = forms.ModelChoiceField(queryset=Product.objects.all())

    class Meta:
        model = Favorite
        fields = ["product"]

substitute/forms/search.py
from django import forms


class SearchForm(forms.Form):
    search = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Saisir un nom de produit'}))

substitute/views/favorite.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect
from django.views.generic.edit import CreateView, DeleteView
from django.views.generic.list import ListView

from substitute.forms.favorite import FavForm
from substitute.models.favorite import Favorite
from substitute.models.product import Product
from substitute.views.utils import get_msg


class AddFavoriteView(CreateView):
    model = Favorite
    form_class = FavForm

    def post(self, request, *args, **kwargs):
        prod = get_object_or_404(Product, pk=kwargs['pk'])
        form = FavForm(request.POST)
        if form.is_valid():
            unsaved_fav = form.save(commit=False)
            unsaved_fav.user = request.user
            unsaved_fav.save()
            messages.success(request, get_msg(prod, "add", "success"))
        else:
            messages.error(request, get_msg(prod, "add", "fail"))

        return redirect(request.META['HTTP_REFERER'])


class RemoveFavoriteView(DeleteView):
    model = Favorite
    form_class = FavForm

    def post(self, request, *args, **kwargs):
        fav = get_object_or_404(Favorite, product=kwargs['pk'], user=request.user)
        form = FavForm(request.POST)
        if form.is_valid():
            fav.delete()
            messages.success(request, get_msg(fav.product, "delete", "success"))
        else:
            messages.error(request, get_msg(fav.product, "delete", "fail"))
        return redirect(request.META['HTTP_REFERER'])


class FavoritesView(ListView):
    http_method_names = ['get', 'options']
    template_name = 'substitute/favorites.html'
    model = Favorite
    paginate_by = 6

    def get_queryset(self):
        return self.request.user.all_favs_prods

substitute/views/home.py
from django.views.generic.base import TemplateView


class HomeView(TemplateView):
    template_name = 'home.html'

substitute/views/product.py
from django.db.models import Count, Q
from django.shortcuts import get_object_or_404, render
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormMixin
from django.views.generic.list import ListView

from substitute.forms.search import SearchForm
from substitute.models.product import Product


class SearchResultView(ListView, FormMixin):
    http_method_names = ['get', 'options']
    form_class = SearchForm
    template_name = 'substitute/search_results.html'
    model = Product
    paginate_by = 6

    def get_queryset(self):
        search_text = self.request.GET.get('search', None)
        if search_text:
            return self.get_prod_by_name(search_text)

    @staticmethod
    def get_prod_by_name(search_text):
        return Product.objects.filter(
                Q(name__icontains=search_text.lower().strip())
            ).order_by('-nutriscore')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('search')
        return context


class ProductDetailView(DetailView):
    model = Product

    def get(self, request, *args, **kwargs):
        product = get_object_or_404(Product, pk=kwargs['pk'])
        substitutes = self._refine_substitutes(product, self._get_substitutes(product))
        context = {'product': product, 'substitutes': substitutes}
        return render(request, 'substitute/product_detail.html', context)

    @staticmethod
    def _get_substitutes(product):
        return Product.objects.annotate(
            common_categories=Count(
                "categories",
                filter=Q(categories__in=product.categories.all())
            )
        ).annotate(
            num_categories=Count("categories")
        )

    def _refine_substitutes(self, product, substitutes):
        no_product_categories = product.categories.all().count()
        substitutes.filter(common_categories=no_product_categories)
        if product.nutriscore == "a":
            substitutes = substitutes.filter(nutriscore__lte=product.nutriscore)
        else:
            substitutes = substitutes.filter(nutriscore__lt=product.nutriscore)

        return substitutes.exclude(
            pk=self.kwargs['pk']
        ).order_by(
            "nutriscore", "num_categories", "-common_categories"
        )[:3]

substitute/views/utils.py
def get_msg(prod, procedure, outcome):
    if procedure == "delete":
        if outcome == "success":
            return (
                "Le produit suivant a bien été supprimé de vos favoris:\n"
                f"{prod}"
            )
        elif outcome == "fail":
            return (
                "Le produit suivant n'a pas été supprimé de vos favoris:\n"
                f"{prod}"
            )
    elif procedure == "add":
        if outcome == "success":
            return (
                "Le produit suivant a bien été enregistré dans vos favoris:\n"
                f"{prod}"
            )
        elif outcome == "fail":
            return (
                "Le produit suivant n'a pas été enregistré dans vos favoris:\n"
                f"{prod}"
            )
    else:
        raise AttributeError("You're not asking for the right message !")

templates/substitute/favorites.html
{% extends "home.html" %}

{% load bootstrap5 %}

{% block title %}Favoris{% endblock title %}

{% block content %}

{% include "substitute/partials/product_list.html" with prod_list=page_obj favorites=True %}

{% block pagination %}
  {% if is_paginated %}
    {% include "substitute/partials/pagination.html" with page_obj=page_obj query=query %}
  {% endif %}
{% endblock pagination %}

{% endblock content %}

templates/substitute/product_detail.html
{% extends "home.html" %}


{% load static %}
{% load bootstrap5 %}

{% block title %}Détail produit de {{ product.name }}{% endblock title %}

{% block content %}
<section class="page-section py-2" id="top-page">
  <div id="product_detail" class="container"  style="background-image: url({{ product.image_url }})">
  </div>
  <div class="container">
    <div class="row align-items-center justify-content-center">
      {{ product.name }}
    </div>
  </div>
</section>

<section class="page-section bg-secondary py-3" id="resultat">
    <div class="container">
      <div class="row text-center">
        <div class="d-flex align-items-center justify-content-center col-md-6">
          {% with "assets/img/nutriscore-"|add:product.nutriscore|add:".svg" as url %}
            <img src="{% static url %}">
          {% endwith %}
        </div>
        <div class="col-md-6">
          <h4>
            Repères nutritionnels pour 100g
          </h4>
          <p>
            <img src="{{ product.image_nutri }}">
          </p>
        </div>
        <div class="text-center">
          <a href="{{ product.url }}" class="btn btn-primary">
            Voir la fiche d'openfoodfacts
          </a>
        </div>
      </div>
    </div>
</section>

<section class="page-section py-3" id="substitutes">
  <div class="container px-4 px-lg-5">
    <div class="row align-items-center justify-content-center">
      {% include "substitute/partials/product_list.html" with prod_list=substitutes detail_view=True %}
    </div>
  </div>
</section>

{% endblock content %}

templates/substitute/search_results.html
{% extends "home.html" %}

{% load bootstrap5 %}

{% block title %}Résultats de la recherche{% endblock title %}

{% block content %}

{% include "substitute/partials/product_list.html" with prod_list=page_obj %}

{% block pagination %}
  {% if is_paginated %}
    {% include "substitute/partials/pagination.html" with page_obj=page_obj query=query %}
  {% endif %}
{% endblock pagination %}

{% endblock content %}